# Site settings
title: Aarne Talman
email: aarne@basement.ai
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: aarnetalman
linkedin_username: talman
instagram_username:
facebook_username:

# Build settings
markdown: kramdown
